Аня:
    01: комплексное, 60
    02: санки, 20
    03: акройога, 17
    04: растяжка, 15

Валера:
    01: лыжи, 47
    02: лыжи, 31
    03: акройога, 17
    04: растяжка, 20

Галина:
    01: комплексное, 40
    02:
    03: ходьба, 149
    04: танцевальная аэробика, 60

Денис:
    01: ориентирование, 63
    02: ориентирование, 72
    03: велосипед, 25
    04:

Женя:
    01: коньки, 63
    02: ходьба, 170
    03: йога, 20
    04: кардио, 21
