Аня:
    01: комплексное, 60
    02: санки, 20
    03: акройога, 17
    04: растяжка, 15
    05: поход, 40
    06: плавание, 60
    07: растяжка, 15
    08: пилатес, 30
    09:
    10:
    11:
    12:
    13: зарядка, 15
    14:
    15: растяжка, 30

Валера:
    01: лыжи, 47
    02: лыжи, 31
    03: акройога, 17
    04:
    05: поход+плавание, 61
    06: плавание, 24
    07:
    08:
    09:
    10:
    11:
    12:
    13:
    14:
    15:

Галина:
    01: комплексное, 40
    02:
    03: ходьба, 149
    04: танцаэробика, 60
    05: гимнастика, 93
    06: растяжка, 17
    07:
    08: йога, 42
    09: йога, 70
    10: йога, 40
    11: йога, 41
    12: йога, 41
    13: йога, 43
    14: йога, 20
    15: йога, 42
    16: йога, 72

Денис:
    01: ориентирование, 63
    02: ориентирование, 72
    03: велосипед, 25
    04: растяжка, 15
    05: ориентирование, 37
    06: бег, 65
    07: растяжка, 15
    08: растяжка, 15
    09: ориентирование, 76
    10: силовая, 15
    11: йога, 20
    12: растяжка, 15
    13: бег, 84
    14: ходьба, 120
    15: растяжка, 15


Женя:
    01: коньки, 63
    02: ходьба, 170
    03: йога, 20
    04: кардио, 21
    05: растяжка, 16
    06: танцаэробика, 27
    07: танцаэробика, 30
    08: HIIT, 23
    09: бег, 21
    10: йога, 19
    11: йога, 20
    12: йога, 20
    13: танцаэробика, 30
    14: йога, 20
    15: йога, 16
    16: йога, 15
