Аня:
    01: комплексное, 60
    02: санки, 20

Валера:
    01: лыжи, 47
    02: лыжи, 31

Галина:
    01: комплексное, 40

Денис:
    01: ориентирование, 63

Женя:
    01: коньки, 63
    02: ходьба, 170
