Аня:
    01: комплексное, 60
    02: санки, 20
    03: акройога, 17

Валера:
    01: лыжи, 47
    02: лыжи, 31
    03: акройога, 17

Галина:
    01: комплексное, 40
    03: ходьба, 149

Денис:
    01: ориентирование, 63
    02: ориентирование, 72

Женя:
    01: коньки, 63
    02: ходьба, 170
    03: йога, 20
